### ISSUE TITLE
Events query fails

### ISSUE THREAD

**Issue by kpedro88** [dmwm/dasgoclient#25]
`events` is listed as a valid key in https://cmsweb.cern.ch/das/services. However, when I try this query in `dasgoclient`, it fails:
```
 dasgoclient -query="events dataset=/QCD_Pt_80to120_TuneCP5_13TeV_pythia8/RunIIFall17MiniAODv2-PU2017_12Apr2018_94X_mc2017_realistic_v14-v1/MINIAODSIM"
panic: runtime error: index out of range

goroutine 1 [running]:
main.process(0x7fff0769930e, 0x81, 0x899100, 0x8991a0, 0x1, 0x1, 0x0, 0x0, 0x8a071c, 0x16, ...)
        /afs/cern.ch/work/v/valya/builds/w700/BUILD/slc6_amd64_gcc700/cms/dasgoclient-binary/v02.01.01/dasgoclient/main.go:389 +0x4022
main.main()
        /afs/cern.ch/work/v/valya/builds/w700/BUILD/slc6_amd64_gcc700/cms/dasgoclient-binary/v02.01.01/dasgoclient/main.go:119 +0x912
```

It is possible to access the same information using `summary` instead, but maybe this failure can be fixed.

**Comment by vkuznet** [comment]
in production

**Comment by vkuznet** [comment]
sorry I put wrong statement (wrong tab)
